name: hierarchy-generation
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - scipy=1.1.0
  - scikit-image=0.18.3
  - pillow
  # profiling
  - snakeviz=2.0.1
  - pip
  - pip:
      # Wasserstein
      - pot==0.8.1
      # guided filter
      - opencv-python
      - opencv-contrib-python
