name: hierarchy-generation
channels:
  - conda-forge
  - defaults
  - pytorch
dependencies:
  - python=3.7
  - pytorch=1.8.0
  - torchvision=0.9.0
  - scipy=1.1.0
  - pip
  - pip:
      - mmcv-full -f https://download.openmmlab.com/mmcv/dist/cpu/torch1.8.0/index.html
      - mmsegmentation
